routes:
  - name: modbus_to_engine
    match:
      topic: "device/modbus/out"
    targets:
      topic: "device/ble/in"
      topic: "device/gpio/in"
      topic: "device/api/in"

  - name: BLE_to_engine
    match:
      topic: "device/BLE/out"
    targets:
      topic: "device/modbus/in"
      topic: "device/gpio/in"
      topic: "device/api/in"

  - name: GPIO_to_engine
    match:      
      topic: "device/GPIO/out"
    targets:
      topic: "device/modbus/in"
      topic: "device/ble/in"
      topic: "device/api/in"
  
  - name: API_to_engine
    match:
      topic: "device/API/out"
    targets:
      topic: "device/modbus/in"
      topic: "device/ble/in"
      topic: "device/gpio/in"
        
